# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 13:07
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='user_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 11, 16, 7, 18, 696527), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(upload_to='news_images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 16, 7, 18, 700530), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='', max_length=5000, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 11, 16, 7, 18, 701530), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фотография товара'),
        ),
        migrations.AlterField(
            model_name='record',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 11, 16, 7, 18, 698528), verbose_name='Дата сохранения'),
        ),
    ]
