# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160611_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo_gallery/')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 13, 15, 4, 31, 997836), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 15, 4, 31, 999837), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 15, 4, 32, 838), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='record',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 13, 15, 4, 31, 998837), verbose_name='Дата сохранения'),
        ),
    ]
