# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160613_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 13, 16, 28, 59, 888589), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 16, 28, 59, 890591), verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 16, 28, 59, 891591), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='record',
            name='save_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 13, 16, 28, 59, 889588), verbose_name='Дата сохранения'),
        ),
    ]
